/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo_estoque.telas;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poo_estoque.servicos.GerarCSV;
import poo_estoque.objetos.Moto;
import poo_estoque.servicos.ImplServicoVeiculos;
import poo_estoque.servicos.SingletonLogin;

/**
 *
 * @author Josué
 */
public class GerenciarMotos extends javax.swing.JFrame {

    EditarMotos editarProduto = new EditarMotos();
    TelaPrincipal desktopPanePrincipal = new TelaPrincipal();
    private Boolean alertEstoq = true;

    public GerenciarMotos() {
        initComponents();
        jTableListaProduto.getColumnModel().getColumn(0).setMinWidth(0);
        jTableListaProduto.getColumnModel().getColumn(0).setMaxWidth(0);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setResizable(false);

        if (!SingletonLogin.getInstance().getCargo().equalsIgnoreCase("Gerente")) {
            jPanelBuscarProduto.remove(jButtonAlterar);
            jPanelBuscarProduto.remove(jButtonDesativarProduto);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanelBuscarProduto = new javax.swing.JPanel();
        jLabelDescricao = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPaneListaProduto = new javax.swing.JScrollPane();
        jTableListaProduto = new javax.swing.JTable();
        jButtonDesativarProduto = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jTextFieldModelo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setTitle("Gerenciar Produto");
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                formComponentRemoved(evt);
            }
        });

        jPanelBuscarProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelDescricao.setText("Modelo");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTableListaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Marca", "Modelo", "Cor", "Ano", "AltAssento", "Estoque", "R$"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaProduto.setToolTipText("Lista Produtos");
        jTableListaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaProdutoMouseClicked(evt);
            }
        });
        jScrollPaneListaProduto.setViewportView(jTableListaProduto);

        jButtonDesativarProduto.setText("Excluir");
        jButtonDesativarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesativarProdutoActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jTextFieldModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldModeloKeyPressed(evt);
            }
        });

        jButton1.setText("Gerar CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarProdutoLayout = new javax.swing.GroupLayout(jPanelBuscarProduto);
        jPanelBuscarProduto.setLayout(jPanelBuscarProdutoLayout);
        jPanelBuscarProdutoLayout.setHorizontalGroup(
            jPanelBuscarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneListaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarProdutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDesativarProduto))
                    .addGroup(jPanelBuscarProdutoLayout.createSequentialGroup()
                        .addComponent(jLabelDescricao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelBuscarProdutoLayout.createSequentialGroup()
                        .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar)))
                .addContainerGap())
        );
        jPanelBuscarProdutoLayout.setVerticalGroup(
            jPanelBuscarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBuscarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneListaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBuscarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDesativarProduto)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBuscarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSair)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        ImplServicoVeiculos servico = new ImplServicoVeiculos();
        try {
            //Obtém a linha selecionada na tabela de resultados
            final int row = jTableListaProduto.getSelectedRow();
            //Verifica se há linha selecionada na tabela
            if (row >= 0) {
                //Obtém a linha selecionada na tabela
                Integer id = (Integer) jTableListaProduto.getValueAt(row, 0);

                //Solicita ao serviço a obtenção do produto a partir do
                //ID selecionado na tabela
//                Moto produto = ServicoMotos.obterProduto(id);
                Moto produto = (Moto) servico.obter(id, 1);
                //Cria uma nova instância da tela de edição,
                //configura o produto selecionado como elemento a
                //ser editado e mostra a tela de edição.
                //Para exibir a tela, é necessário adicioná-la ao
                //componente de desktop, o "pai" da janela corrente
                editarProduto.dispose();
                editarProduto = new EditarMotos();
                editarProduto.setProduto(produto);
                //this.getParent().add(editarProduto);
                this.editarProduto.setVisible(true);
                //this.openFrameInCenter(editarProduto);
                editarProduto.toFront();

            } else {
                JOptionPane.showMessageDialog(this, "Selecione um produto para alterar.");
            }
        } catch (Exception e) {
            //Se ocorrer algum erro técnico, mostra-o no console,
            //mas esconde-o do usuário
            e.printStackTrace();
            //Exibe uma mensagem de erro genérica ao usuário
            JOptionPane.showMessageDialog(rootPane, "Não é possível "
                    + "exibir os detalhes deste produto.",
                    "Erro ao abrir detalhe", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        boolean resultDesc = false;

        Cursor cur = getCursor();
        try {

            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            //Solicita a atualização da lista com o novo critério
            //de pesquisa (ultimaPesquisa)
            resultDesc = refreshList();
        } catch (Exception e) {
            setCursor(cur);
            //Exibe mensagens de erro na fonte de dados e para o listener
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                    "Falha ao obter lista", JOptionPane.ERROR_MESSAGE);
            return;
        }
        setCursor(cur);
        //Exibe mensagem de erro caso a pesquisa não tenha resultados
        if (!resultDesc) {
            JOptionPane.showMessageDialog(rootPane, "A pesquisa não retornou "
                    + "resultados ", "Sem resultados",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableListaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaProdutoMouseClicked
        ImplServicoVeiculos servico = new ImplServicoVeiculos();
        if (evt.getClickCount() == 2) {
            try {
                //Obtém a linha selecionada da tabela de resultados
                final int row = jTableListaProduto.getSelectedRow();
                //Obtém o valor do ID da coluna "ID" da tabela de resultados
                Integer id = (Integer) jTableListaProduto.getValueAt(row, 0);

                //Com o ID da coluna, chama o serviço de produto para
                //obter o produto com dados atualizados do mock
                Moto prod = (Moto) servico.obter(id, 1);

                //Cria uma nova instância da tela de edição,
                //configura o produto selecionado como elemento a
                //ser editado e mostra a tela de edição.
                //Para exibir a tela, é necessário adicioná-la ao
                //componente de desktop, o "pai" da janela corrente
                editarProduto.dispose();
                editarProduto = new EditarMotos();
                editarProduto.setProduto(prod);
                this.getParent().add(editarProduto);
                this.editarProduto.setVisible(true);
                editarProduto.toFront();
            } catch (Exception e) {
                //Se ocorrer algum erro técnico, mostra-o no console,
                //mas esconde-o do usuário
                e.printStackTrace();
                //Exibe uma mensagem de erro genérica ao usuário
                JOptionPane.showMessageDialog(rootPane, "Não é possível "
                        + "exibir os detalhes deste produto.",
                        "Erro ao abrir detalhe", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTableListaProdutoMouseClicked

    private void jButtonDesativarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesativarProdutoActionPerformed
        ImplServicoVeiculos servico = new ImplServicoVeiculos();
        if (jTableListaProduto.getSelectedRow() >= 0) {

            //Obtém a linha do item selecionado
            final int row = jTableListaProduto.getSelectedRow();
            //Obtém a descrição do produto da linha indicada para exibição;
            //de mensagem de confirmação de exclusão utilizando sua descrição.
            String prod = (String) jTableListaProduto.getValueAt(row, 1);
            //Mostra o diálogo de confirmação de exclusão
            int resposta = JOptionPane.showConfirmDialog(rootPane,
                    "Excluir o produto \"" + prod + "\"?",
                    "Confirmar exclusão", JOptionPane.YES_NO_OPTION);
            //Se o valor de resposta for "Sim" para a exclusão
            if (resposta == JOptionPane.YES_OPTION) {

                try {
                    //Obtém o ID do produto
                    Integer idProd = (Integer) jTableListaProduto.getValueAt(row, 0);
                    //Solicita ao serviço a inativação do produto com o ID
                    //ServicoMotos.excluirProduto(idProd);
                    servico.Excluir(idProd, 1);

                    JOptionPane.showMessageDialog(this, "Produto excluído com sucesso.");
                    //Atualiza a lista após a "exclusão"
                    this.refreshList();
                } catch (Exception e) {

                    e.printStackTrace();
                    //Exibe uma mensagem de erro genérica ao usuário
                    JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                            "Falha na Exclusão", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o produto que deseja excluir.");
        }
    }//GEN-LAST:event_jButtonDesativarProdutoActionPerformed

    private void jTextFieldModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldModeloKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonBuscar.doClick();
        }
    }//GEN-LAST:event_jTextFieldModeloKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTableListaProduto.getModel().getRowCount() > 0) {
            GerarCSV export = new GerarCSV();
            String caminho = System.getProperty("user.home");
            export.toExcel(jTableListaProduto, new File(caminho + "/Documents/Motos.csv"));
            JOptionPane.showMessageDialog(this, "Relatório 'Motos.csv' gerado com sucesso nos seus documentos!");
        } else {
            JOptionPane.showMessageDialog(this, "Não há dados para serem exportados.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentRemoved
        try {
            this.refreshList();
        } catch (Exception ex) {
            Logger.getLogger(GerenciarMotos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentRemoved

    public boolean refreshList() throws Exception {
        ImplServicoVeiculos servico = new ImplServicoVeiculos();
        //List<Moto> resultado = ServicoMotos.procurarProduto(jTextFieldModelo.getText());
        List<Object> resultado = servico.Procurar(jTextFieldModelo.getText(), 1);

        DefaultTableModel model = (DefaultTableModel) jTableListaProduto.getModel();

        model.setRowCount(0);

        if (resultado == null || resultado.size() <= 0) {
            return false;
        }

        int alertaEstoq = 6;
        String desc = null;

        for (int i = 0; i < resultado.size(); i++) {
            Moto produto = (Moto) resultado.get(i);
            if (produto != null) {
                Object[] row = new Object[9];
                row[0] = produto.getId();
                row[1] = produto.getMarca();
                row[2] = produto.getModelo();
                row[3] = produto.getCor();
                row[4] = produto.getAno();
                row[5] = produto.getAlturaAssento();
                row[6] = produto.getQtd();
                row[7] = produto.getPreco();
                model.addRow(row);
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonDesativarProduto;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JPanel jPanelBuscarProduto;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPaneListaProduto;
    private javax.swing.JTable jTableListaProduto;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables

}
