/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo_estoque.telas;

import java.awt.Dimension;
import java.awt.Toolkit;
import poo_estoque.servicos.SingletonLogin;

/**
 *
 * @author Josué
 */
public class TelaPrincipal extends javax.swing.JFrame {

    CadastrarCarros cadastrarProduto = null;
    GerenciarCarros gerenciarProduto = null;
    GerenciarMotos gerenciarMotos = null;
    CadastrarMotos cadastrarMotos = null;
    TelaLogin login = null;

    public GerenciarCarros getConsultarProduto() {
        return gerenciarProduto;
    }

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        jTextFieldUsuario.setText("Usuário: " + SingletonLogin.getInstance().getNome() + " " + SingletonLogin.getInstance().getCargo());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        this.setResizable(false);

        if (!SingletonLogin.getInstance().getCargo().equalsIgnoreCase("Gerente")) {
            jButtonCadastroMoto.setEnabled(false);
            jButtonCadastroCarro.setEnabled(false);
        }
        this.setTitle("Estoque - Carros e Motos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanePrincipal = new javax.swing.JPanel();
        jButtonCadastroMoto = new javax.swing.JButton();
        jButtonCadastroCarro = new javax.swing.JButton();
        jButtonConsultaMoto = new javax.swing.JButton();
        jButtonConsultaCarro = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPanePrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonCadastroMoto.setText("Cadastrar Moto");
        jButtonCadastroMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroMotoActionPerformed(evt);
            }
        });

        jButtonCadastroCarro.setText("Cadastrar Carro");
        jButtonCadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCarroActionPerformed(evt);
            }
        });

        jButtonConsultaMoto.setText("Consultar Moto");
        jButtonConsultaMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaMotoActionPerformed(evt);
            }
        });

        jButtonConsultaCarro.setText("Consultar Carro");
        jButtonConsultaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaCarroActionPerformed(evt);
            }
        });

        jTextFieldUsuario.setEditable(false);

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopPanePrincipalLayout = new javax.swing.GroupLayout(desktopPanePrincipal);
        desktopPanePrincipal.setLayout(desktopPanePrincipalLayout);
        desktopPanePrincipalLayout.setHorizontalGroup(
            desktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPanePrincipalLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(desktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastroMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(desktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonConsultaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jButtonConsultaMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(desktopPanePrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addGap(26, 26, 26))
        );
        desktopPanePrincipalLayout.setVerticalGroup(
            desktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPanePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout))
                .addGap(25, 25, 25)
                .addGroup(desktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(desktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultaMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        desktopPanePrincipal.getAccessibleContext().setAccessibleName("Tela Principal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCarroActionPerformed
        cadastrarProduto = new CadastrarCarros();
        cadastrarProduto.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroCarroActionPerformed

    private void jButtonConsultaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaCarroActionPerformed
        gerenciarProduto = new GerenciarCarros();
        gerenciarProduto.setVisible(true);
    }//GEN-LAST:event_jButtonConsultaCarroActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        login = new TelaLogin();
        login.setVisible(true);
        SingletonLogin.getInstance().setCargo("0");
        this.dispose();

    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonCadastroMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroMotoActionPerformed
        cadastrarMotos = new CadastrarMotos();
        cadastrarMotos.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroMotoActionPerformed

    private void jButtonConsultaMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaMotoActionPerformed
        gerenciarMotos = new GerenciarMotos();
        gerenciarMotos.setVisible(true);
    }//GEN-LAST:event_jButtonConsultaMotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel desktopPanePrincipal;
    private javax.swing.JButton jButtonCadastroCarro;
    private javax.swing.JButton jButtonCadastroMoto;
    private javax.swing.JButton jButtonConsultaCarro;
    private javax.swing.JButton jButtonConsultaMoto;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
